version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 11
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
